name: Build_iOS
on: [push]

jobs:
  build:
    runs-on: macos-latest 
    steps:
      - uses: actions/checkout@v4

      # ESTO ES PARA VER DONDE ESTA EL BUILDOZER.SPEC
      - name: ¿Donde estan mis archivos?
        run: |
          pwd
          ls -R

      - name: Setup_Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install_Tools
        run: |
          pip install --upgrade pip
          pip install Cython buildozer kivy-ios

      - name: Build_IPA
        run: |
          # Si el archivo esta en una carpeta, aqui fallara
          # Pero el paso de arriba nos dira EXACTO donde moverlo
          buildozer ios debug
        
      - name: Upload_Result
        uses: actions/upload-artifact@v4
        with:
          name: App-Mao-Tech
          path: bin/*.ipa
